/**
 * Device linking by ECDH key agreement.
 *
 * Lets a new device receive the vault secret without anyone typing it, and
 * without the server ever being able to read it.
 *
 *   new device                    server                 existing device
 *   ----------                    ------                 ---------------
 *   generate (privA, pubA)
 *   register pubA          ---->  store pending
 *   show QR containing pubA  ....... out of band ....>    scan / paste
 *                                                         verify fingerprint
 *                                                         generate (privB, pubB)
 *                                                         shared = ECDH(privB, pubA)
 *                                 store  <----            pubB + wrap(shared, secret)
 *   poll  <----  deliver
 *   shared = ECDH(privA, pubB)
 *   unwrap secret
 *
 * The server relays two public keys and one ciphertext. It cannot derive the
 * shared secret from public keys alone.
 *
 * The MITM it *could* attempt is substituting its own public key for pubA.
 * That is why pubA travels out of band -- through a camera or a human paste --
 * and why the approving side is shown a fingerprint of the key it actually
 * received. If the server swapped the key, the fingerprints disagree.
 */

import { fromBase64Url, toBase64Url } from "./base64";

const CURVE = "P-256";
const IV_BYTES = 12;

export interface LinkKeypair {
  readonly privateKey: CryptoKey;
  /** Raw uncompressed point, base64url. Safe to publish. */
  readonly publicKey: string;
}

/** Generated by the joining device, used once, never stored. */
export async function createLinkKeypair(): Promise<LinkKeypair> {
  // Cast because the Workers type definitions declare the union return for
  // generateKey/exportKey rather than narrowing by algorithm the way the DOM
  // lib does. An ECDH generateKey always yields a pair, and a "raw" export is
  // always an ArrayBuffer.
  const pair = (await crypto.subtle.generateKey(
    { name: "ECDH", namedCurve: CURVE },
    true,
    ["deriveBits"],
  )) as CryptoKeyPair;

  const raw = (await crypto.subtle.exportKey(
    "raw",
    pair.publicKey,
  )) as ArrayBuffer;
  return {
    privateKey: pair.privateKey,
    publicKey: toBase64Url(new Uint8Array(raw)),
  };
}

async function importPublicKey(publicKey: string): Promise<CryptoKey> {
  return crypto.subtle.importKey(
    "raw",
    fromBase64Url(publicKey),
    { name: "ECDH", namedCurve: CURVE },
    false,
    [],
  );
}

/**
 * Both public keys are bound into the HKDF info, so a transcript with a
 * swapped key derives a different secret and the unwrap fails closed.
 */
async function sharedKey(
  privateKey: CryptoKey,
  peerPublicKey: string,
  joinerPublicKey: string,
  approverPublicKey: string,
): Promise<CryptoKey> {
  const peer = await importPublicKey(peerPublicKey);

  // The Workers type definitions name this field `$public` (a reserved word in
  // the IDL they generate from) while the DOM lib and the actual runtime both
  // use `public`. Setting both keeps this one file compiling against either.
  const ecdh = {
    name: "ECDH",
    public: peer,
    $public: peer,
  } as Parameters<typeof crypto.subtle.deriveBits>[0];

  const bits = await crypto.subtle.deriveBits(ecdh, privateKey, 256);

  const material = await crypto.subtle.importKey("raw", bits, "HKDF", false, [
    "deriveKey",
  ]);

  return crypto.subtle.deriveKey(
    {
      name: "HKDF",
      hash: "SHA-256",
      salt: new Uint8Array(0),
      info: new TextEncoder().encode(
        `clipsync:link:v1:${joinerPublicKey}:${approverPublicKey}`,
      ),
    },
    material,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt", "decrypt"],
  );
}

/** Called by the approving device. Returns the sealed secret. */
export async function sealToDevice(
  joinerPublicKey: string,
  secret: string,
): Promise<{ envelope: string; approverPublicKey: string }> {
  const ephemeral = await createLinkKeypair();
  const key = await sharedKey(
    ephemeral.privateKey,
    joinerPublicKey,
    joinerPublicKey,
    ephemeral.publicKey,
  );

  const iv = crypto.getRandomValues(new Uint8Array(IV_BYTES));
  const ct = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv },
    key,
    new TextEncoder().encode(secret),
  );

  return {
    envelope: `l1.${toBase64Url(iv)}.${toBase64Url(new Uint8Array(ct))}`,
    approverPublicKey: ephemeral.publicKey,
  };
}

export class LinkError extends Error {}

/** Called by the joining device once the server returns an approval. */
export async function openFromDevice(
  keypair: LinkKeypair,
  approverPublicKey: string,
  envelope: string,
): Promise<string> {
  const parts = envelope.split(".");
  if (parts.length !== 3 || parts[0] !== "l1") {
    throw new LinkError("unsupported link envelope");
  }

  const key = await sharedKey(
    keypair.privateKey,
    approverPublicKey,
    keypair.publicKey,
    approverPublicKey,
  );

  try {
    const pt = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv: fromBase64Url(parts[1]!) },
      key,
      fromBase64Url(parts[2]!),
    );
    return new TextDecoder().decode(pt);
  } catch {
    throw new LinkError(
      "cannot open the linking payload -- the key was substituted or corrupted",
    );
  }
}

/**
 * Six digits, grouped, derived from the joining device's public key. Shown on
 * both ends so a human can confirm they match. This is the check that closes
 * the substitution attack when the key was pasted rather than scanned.
 */
export async function fingerprint(publicKey: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    fromBase64Url(publicKey),
  );
  const bytes = new Uint8Array(digest);
  const n =
    ((bytes[0]! << 16) | (bytes[1]! << 8) | bytes[2]!) % 1_000_000;
  const s = n.toString().padStart(6, "0");
  return `${s.slice(0, 3)}-${s.slice(3)}`;
}
