/**
 * Device linking by ECDH key agreement.
 *
 * Lets a new device receive the vault secret without anyone typing it, and
 * without the server ever being able to read it.
 *
 *   new device                    server                 existing device
 *   ----------                    ------                 ---------------
 *   generate (privA, pubA)
 *   register pubA          ---->  store pending
 *   show QR containing pubA  ....... out of band ....>    scan / paste
 *                                                         verify fingerprint
 *                                                         generate (privB, pubB)
 *                                                         shared = ECDH(privB, pubA)
 *                                 store  <----            pubB + wrap(shared, secret)
 *   poll  <----  deliver
 *   shared = ECDH(privA, pubB)
 *   unwrap secret
 *
 * The server relays two public keys and one ciphertext. It cannot derive the
 * shared secret from public keys alone.
 *
 * The MITM it *could* attempt is substituting its own public key for pubA.
 * That is why pubA travels out of band -- through a camera or a human paste --
 * and why the approving side is shown a fingerprint of the key it actually
 * received. If the server swapped the key, the fingerprints disagree.
 */

import { fromBase64Url, toBase64Url } from "./base64";
import { createEcdhKeypair, ecdhAesKey, type EcdhKeypair } from "./ecdh";

const IV_BYTES = 12;

export type LinkKeypair = EcdhKeypair;

/** Generated by the joining device, used once, never stored. */
export async function createLinkKeypair(): Promise<LinkKeypair> {
  return createEcdhKeypair(true);
}

/**
 * Both public keys are bound into the HKDF info, so a transcript with a
 * swapped key derives a different secret and the unwrap fails closed.
 */
function sharedKey(
  privateKey: CryptoKey,
  peerPublicKey: string,
  joinerPublicKey: string,
  approverPublicKey: string,
): Promise<CryptoKey> {
  return ecdhAesKey(
    privateKey,
    peerPublicKey,
    `clipsync:link:v1:${joinerPublicKey}:${approverPublicKey}`,
  );
}

/** Called by the approving device. Returns the sealed secret. */
export async function sealToDevice(
  joinerPublicKey: string,
  secret: string,
): Promise<{ envelope: string; approverPublicKey: string }> {
  const ephemeral = await createLinkKeypair();
  const key = await sharedKey(
    ephemeral.privateKey,
    joinerPublicKey,
    joinerPublicKey,
    ephemeral.publicKey,
  );

  const iv = crypto.getRandomValues(new Uint8Array(IV_BYTES));
  const ct = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv },
    key,
    new TextEncoder().encode(secret),
  );

  return {
    envelope: `l1.${toBase64Url(iv)}.${toBase64Url(new Uint8Array(ct))}`,
    approverPublicKey: ephemeral.publicKey,
  };
}

export class LinkError extends Error {}

/** Called by the joining device once the server returns an approval. */
export async function openFromDevice(
  keypair: LinkKeypair,
  approverPublicKey: string,
  envelope: string,
): Promise<string> {
  const parts = envelope.split(".");
  if (parts.length !== 3 || parts[0] !== "l1") {
    throw new LinkError("unsupported link envelope");
  }

  const key = await sharedKey(
    keypair.privateKey,
    approverPublicKey,
    keypair.publicKey,
    approverPublicKey,
  );

  try {
    const pt = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv: fromBase64Url(parts[1]!) },
      key,
      fromBase64Url(parts[2]!),
    );
    return new TextDecoder().decode(pt);
  } catch {
    throw new LinkError(
      "cannot open the linking payload -- the key was substituted or corrupted",
    );
  }
}

/**
 * Six digits, grouped, derived from the joining device's public key. Shown on
 * both ends so a human can confirm they match. This is the check that closes
 * the substitution attack when the key was pasted rather than scanned.
 */
export async function fingerprint(publicKey: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    fromBase64Url(publicKey),
  );
  const bytes = new Uint8Array(digest);
  const n =
    ((bytes[0]! << 16) | (bytes[1]! << 8) | bytes[2]!) % 1_000_000;
  const s = n.toString().padStart(6, "0");
  return `${s.slice(0, 3)}-${s.slice(3)}`;
}
